spring:
  cloud:
    azure:
      credential:
        client-id: ${AZURE_CLIENT_ID}
        client-secret: ${AZURE_CLIENT_SECRET}
      profile:
        tenant-id: ${AZURE_TENANT_ID}
      keyvault:
        secret:
          # Spring Cloud Azure v5.16.0 має іншу структуру ніж v4.x.x
          property-sources:
            - name: my-keyvault
              endpoint: ${AZURE_ENDPOINT}